[project]
name = "day5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Soumyajit Behera", email = "soumyajitbehera61@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "groq>=1.6.0",
    "pydantic>=2.13.4",
    "pydocx>=0.9.10",
    "pypdf>=6.16.1",
    "python-docx>=1.2.0",
]

[project.scripts]
day5 = "day5:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
